create sequence public.task_id_seq as integer;

create table public.task
(
    id          integer generated by default as identity
        constraint task_pk
            primary key,
    name        varchar(64)             not null,
    type        varchar(64)             not null,
    done        boolean                 not null,
    priority    varchar(32)           not null,
    created     timestamp default now() not null,
    updated     timestamp default now() not null,
    description varchar(256)
);
